# Generated by Django 5.1.1 on 2024-10-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=300)),
                ('subject', models.CharField(max_length=200)),
                ('messages', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'Apply_contact',
                'verbose_name_plural': 'Apply_contacts',
            },
        ),
    ]
