# Generated by Django 5.1.1 on 2024-10-02 15:53

import joobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(upload_to=joobs.models.upload_job)),
                ('place', models.CharField(max_length=200)),
                ('type_job', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('vacancy', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=900)),
                ('qualifications', models.TextField(max_length=900)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
