# Generated by Django 5.1.1 on 2024-10-03 19:30

import joobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=300)),
                ('web', models.URLField(max_length=700)),
                ('cv', models.FileField(upload_to=joobs.models.upload_cv)),
                ('cover', models.TextField(max_length=700, null=True)),
            ],
            options={
                'verbose_name': 'Apply',
                'verbose_name_plural': 'Applies',
            },
        ),
    ]
