# Generated by Django 5.1.1 on 2024-10-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joobs', '0003_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cover',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='web',
            field=models.CharField(max_length=700),
        ),
    ]
